name: DEPLOY-MAIN
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            # Switch Node.js version
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 16
            node -v
            cd apps/tequila
            npm i
            npm run build 
            pm2 start ecosystem.config.js --only tquilaDevelopment